### ISSUE TITLE
Como organizador de grupo, solicito realizar una revisión al diagrama de objetos, tomando en cuenta los cambios realizados en el diagrama de clases.

### ISSUE THREAD

**Issue by TheMoys** [TheMoys/24-25-IdSw1-SDR#12]
- [x] Definir los atributos que tendrán las entidades del sistema.
- [x] Ejemplificar con un caso práctico los atributos de las entidades.

**Comment by SantiGT1503** [comment]
Se han hecho los cambios solicitados. Quedo atento a cualquier solicitud de cambio
