### ISSUE TITLE
Como organizador de grupo, solicito identificar los principales actores que atacan al sistema.

### ISSUE THREAD

**Issue by TheMoys** [TheMoys/24-25-IdSw1-SDR#20]
**Criterios de aceptación:**

- [ ] Identificar los principales actores que atacan al sistema y enlistarlos.
- [ ] Hacer un README.md con un diagrama .puml en el que se vean reflejados los actores.

**Comment by SantiGT1503** [comment]
Haciendo una pequeña vuelta de los posibles actores que atacan al sistema, he encontrado que algunos pueden ser:
- Administrador del sistema (Gestiona usuarios, permisos y configuraciones general)
- Usuario Autorizado Externo (Personal externo a la institución que tenga permiso para interactuar)
- Usuario (Personal de la institución que recibe o envía y recibe documentos)

**Comment by TheMoys** [comment]
Concuerdo con @SantiGT1503, solo habrá que ponerse de acuerdo en los nombres para estandarizarlos, también hace falta agregar al actor tiempo que será el responsable de atacar al sistema con acciones automáticas.
