### ISSUE TITLE
Como organizador de grupo, solicito identificar los principales casos de uso que presenta el sistema.

### ISSUE THREAD

**Issue by TheMoys** [TheMoys/24-25-IdSw1-SDR#21]
**Criterios de aceptación:**

- [x] Identificar los principales casos de uso del sistema.
- [x] Representarlos en un diagrama .puml y agregarlos a un README.md

**Comment by SantiGT1503** [comment]
Haciendo una pequeña vuelta de los posibles casos de uso, he encontrado que algunos pueden ser:
- Gestionar Documentos
- Enviar Documentos (Se envía un documento a un destinatario, únicamente para actores que pueden enviar documentos)
- Recibir documentos (Esto únicamente en los actores que reciben documentos)
- Firmar Documentos (Esto únicamente a los casos que se solicitan firma y a los actores que reciben documentos)
- Notificaciones y Recordatorios (Con los lineamientos ajustados para las notificaciones de los documentos)

**Comment by TheMoys** [comment]
Me parecen bien los casos de uso @SantiGT1503, solo haría falta agregar el CRUD de usuarios y especificar un poco más al momento de gestionar los documentos (agregar casos de uso para confirmar de lectura, abrir mensaje, etc)

**Comment by diegojiimenez** [comment]
@TheMoys @SantiGT1503 Concuerdo con ambos, también pienso que faltaría separar los casos de uso dependiendo del usuario y sus permisos.
