### ISSUE TITLE
Como organizador de grupo, solicito realizar el diagrama de contexto para el actor "Responsable"

### ISSUE THREAD

**Issue by TheMoys** [TheMoys/24-25-IdSw1-SDR#28]
**Criterios de aceptación:**

- [ ] Utilizar los casos de uso para movilizarse entre los estados
- [x] Crear un README.md en el que se pueda visualizar el diagrama.

**Comment by SantiGT1503** [comment]
Se ha concluido con la creación del diagrama de contexto para el responsable. Quedo a la espera de alguna solicitud de cambio

**Comment by diegojiimenez** [comment]
@SantiGT1503 @TheMoys, Estaba revisando los diagramas de contexto y pude notar que existe un menú principal que no se sabe que contiene, y si solo contiene los mensajes listados es mejor que se inicie de una vez en los mensajes y ya luego poder ir a las categorias y a los usuarios, hay que revisar esa parte.
Y por otro lado tambien estaba viendo que no se agregó el caso de uso para descargar el registro de los envios y las confirmaciones siendo un remitente.

**Comment by SantiGT1503** [comment]
Se ha hecho las correcciones propuestas. Quedo atento a cualquier otra modificación solicitada
